### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by 4c0d3r** [peolic/videohashes#1]
Not sure if I need to install ffmpeg sources to build this....   but I'm trying to use these as a submodule of https://github.com/theporndatabase/namer and I'd need to build it in GitHub actions to ensure code cleanliness.

When I've try to build locally:

```
$ make build
GOOS=windows GOARCH=amd64 EXTRA_LDFLAGS='-extldflags=-static -s -w' \
		go build -o dist/videohashes.exe ./cmd/videohashes
# github.com/peolic/videohashes/internal
internal/common.go:40:23: videoFile.Duration undefined (type *ffmpeg.VideoFile has no field or method Duration)
make: *** [windows] Error 2
```

Any pointers on how to build locally would be appreciated.

**Comment by peolic** [comment]
Your code is using a newer version of the Stash `develop` branch that has changes I haven't had a chance to incorporate.

**Comment by 4c0d3r** [comment]
Confirmed it builds and generates hashes -- not sure if those hashes are "correct"
